# -*- coding: utf-8 -*-
"""Based example of a personalized learning system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AK-MtwdRFTt5rc9irloQjiWhQGe9LuhE
"""

# Define a dictionary of learning materials and their difficulty levels
learning_materials = {
    "easy_math": {
        "content": "Basic arithmetic operations like addition and subtraction",
        "difficulty": "easy"
    },
    "medium_math": {
        "content": "Multiplication and division of multi - digit numbers",
        "difficulty": "medium"
    },
    "hard_math": {
        "content": "Algebraic equations and problem - solving",
        "difficulty": "hard"
    },
    "easy_language": {
        "content": "Vocabulary building and simple sentence construction",
        "difficulty": "easy"
    },
    "medium_language": {
        "content": "Grammar rules and paragraph writing",
        "difficulty": "medium"
    },
    "hard_language": {
        "content": "Literature analysis and advanced composition",
        "difficulty": "hard"
    }
}


# Simulate a quiz and return the score
def take_quiz():
    import random
    score = random.randint(0, 100)
    return score


# Determine the appropriate learning material based on the score
def recommend_material(score, subject):
    if score < 30:
        if subject == "math":
            return learning_materials["easy_math"]
        else:
            return learning_materials["easy_language"]
    elif score < 70:
        if subject == "math":
            return learning_materials["medium_math"]
        else:
            return learning_materials["medium_language"]
    else:
        if subject == "math":
            return learning_materials["hard_math"]
        else:
            return learning_materials["hard_language"]


# Main function to run the personalized learning system
def personalized_learning():
    subject = input("Please enter the subject (math or language): ")
    score = take_quiz()
    print(f"Your quiz score is: {score}")
    recommended = recommend_material(score, subject)
    print(f"Based on your score, we recommend the following learning material:")
    print(f"Content: {recommended['content']}")
    print(f"Difficulty: {recommended['difficulty']}")


if __name__ == "__main__":
    personalized_learning()